#!/bin/sh

function usage()
{
    echo "Usage: resctrl [create|create2|delete] name"
    exit 0
}

function create()
{
    echo "creating... ${1}"

    TARGET_DIR="resource/${1}"
    INSERT_LINE=$((`grep -n "Hook area" main.py | awk -F: '{print $1}'`-2))

    prefix_part=$(tr a-z A-Z <<< ${1:0:1})${1:1}

    if [ ! -d ${TARGET_DIR} ]; then
        mkdir ${TARGET_DIR}
        touch ${TARGET_DIR}/__init__.py
        
        if [ "${2}" = "type2" ]; then
            cp template/resource_2.py ${TARGET_DIR}/${1}_resource.py

            sed -i "s/MODEL/${prefix_part}Model/g" ${TARGET_DIR}/${1}_resource.py
            sed -i "s/VIEW/${prefix_part}View/g" ${TARGET_DIR}/${1}_resource.py
        else
            cp template/resource.py ${TARGET_DIR}/${1}_resource.py
        fi

        cp template/model.py ${TARGET_DIR}/${1}_model.py
        cp template/view.py ${TARGET_DIR}/${1}_view.py

        sed -i "s/RESOURCE/${prefix_part}Resource/g" ${TARGET_DIR}/${1}_resource.py
        sed -i "${INSERT_LINE}a root.${1} = ${prefix_part}Resource()" main.py
        sed -i "${INSERT_LINE}a from ${1}.${1}_resource import ${prefix_part}Resource" main.py
    fi
}

function delete()
{
    echo "deleting... ${1}"

    TARGET_DIR="resource/${1}"

    prefix_part=$(tr a-z A-Z <<< ${1:0:1})${1:1}

    if [ -d ${TARGET_DIR} ]; then
        rm -rf ${TARGET_DIR}

        DELETE_LINE=`grep -n "root.${1}" main.py | awk -F: '{print $1}'`
        sed -i "${DELETE_LINE}d" main.py

        DELETE_LINE=`grep -n "from ${1}.${1}_resource" main.py | awk -F: '{print $1}'`
        sed -i "${DELETE_LINE}d" main.py
    fi
}

if [ ${#} != 2 ]; then
    usage
fi

case ${1} in
    "create")
        create ${2}
        ;;
    "create2")
        create ${2} "type2"
        ;;
    "delete")
        delete ${2}
        ;;
    *)
        usage
        ;;
esac

exit 0
