#!/bin/sh

function usage()
{
    echo "Usage: taskctrl [create|delete] name"
    exit 0
}

function create()
{
    echo "creating... ${1}"

    TARGET_DIR="background/${1}"
    INSERT_LINE=$((`grep -n "]" background/__init__.py | awk -F: '{print $1}'`-1))

    if [ ! -d ${TARGET_DIR} ]; then
        mkdir ${TARGET_DIR}
        touch ${TARGET_DIR}/__init__.py
        cp template/task.py ${TARGET_DIR}/task.py

        sed -i "${INSERT_LINE}a \ \ \ \ '${1}'," background/__init__.py
    fi
}

function delete()
{
    echo "deleting... ${1}"

    TARGET_DIR="background/${1}"

    if [ -d ${TARGET_DIR} ]; then
        rm -rf ${TARGET_DIR}

        DELETE_LINE=`grep -n "${1}" background/__init__.py | awk -F: '{print $1}'`
        sed -i "${DELETE_LINE}d" background/__init__.py
    fi
}

if [ ${#} != 2 ]; then
    usage
fi

case ${1} in
    "create")
        create ${2}
        ;;
    "delete")
        delete ${2}
        ;;
    *)
        usage
        ;;
esac

exit 0
