#!/bin/bash

function usage()
{
    echo "Usage: resctrl app_name [create|create2|delete] name"
    exit 0
}

function create()
{
    echo "creating... ${2}"

    PRE_PATH="apps/${1}"
    TARGET_DIR="${PRE_PATH}/resource/${2}"
    INSERT_LINE=$((`grep -n "Hook area" ${PRE_PATH}/main.py | awk -F: '{print $1}'`-2))

    prefix_part=$(tr a-z A-Z <<< ${2:0:1})${2:1}

    if [ ! -d ${TARGET_DIR} ]; then
        mkdir ${TARGET_DIR}
        touch ${TARGET_DIR}/__init__.py
        
        if [ "${3}" = "type2" ]; then
            cp template/resource_2.py ${TARGET_DIR}/${2}_resource.py

            sed -i "s/MODEL/${prefix_part}Model/g" ${TARGET_DIR}/${2}_resource.py
            sed -i "s/VIEW/${prefix_part}View/g" ${TARGET_DIR}/${2}_resource.py
        else
            cp template/resource.py ${TARGET_DIR}/${2}_resource.py
        fi

        cp template/model.py ${TARGET_DIR}/${2}_model.py
        cp template/view.py ${TARGET_DIR}/${2}_view.py

        sed -i "s/RESOURCE/${prefix_part}Resource/g" ${TARGET_DIR}/${2}_resource.py
        sed -i "${INSERT_LINE}a root.${2} = ${prefix_part}Resource()" ${PRE_PATH}/main.py
        sed -i "${INSERT_LINE}a from ${2}.${2}_resource import ${prefix_part}Resource" ${PRE_PATH}/main.py
    fi
}

function delete()
{
    echo "deleting... ${2}"

    PRE_PATH="apps/${1}"
    TARGET_DIR="${PRE_PATH}/resource/${2}"

    prefix_part=$(tr a-z A-Z <<< ${2:0:1})${2:1}

    if [ -d ${TARGET_DIR} ]; then
        rm -rf ${TARGET_DIR}

        DELETE_LINE=`grep -n "root.${2}" ${PRE_PATH}/main.py | awk -F: '{print $1}'`
        sed -i "${DELETE_LINE}d" ${PRE_PATH}/main.py

        DELETE_LINE=`grep -n "from ${2}.${2}_resource" ${PRE_PATH}/main.py | awk -F: '{print $1}'`
        sed -i "${DELETE_LINE}d" ${PRE_PATH}/main.py
    fi
}

if [ ${#} != 3 ]; then
    usage
fi

case ${2} in
    "create")
        create ${1} ${3}
        ;;
    "create2")
        create ${1} ${3} "type2"
        ;;
    "delete")
        delete ${1} ${3}
        ;;
    *)
        usage
        ;;
esac

exit 0
